### ISSUE TITLE
Which token should i use for "Spotify Account AccessToken ReGenerate" ?

### ISSUE THREAD

**Issue by PatateBoulette** [kardespro/discord-api-endpoints#1]
Hi, I tried some get requests on `https://discord.com/api/v9/users/@me/connections/spotify/yourusername/access-token` 
I tried with :

- Spotify access token
- Discord user token
- Discord bot token (With connections scope enabled)

I always get this :
```
{
    "message": "401: Unauthorized",
    "code": 0
}
```

Here's my code if it can help :
```
axios.get(`https://discord.com/api/v9/users/@me/connections/spotify/${username}/access-token`, {
    headers: {
        Authorization: `Bearer ${access_token}`
    }
})
.catch(err => {
    console.log(err.response.data);
})
.then(response => {
    console.log(response);
});
```

I changed the `access_token` variable to three different types of tokens as I mentioned above but it didn't work.

**Comment by kardespro** [comment]
Hello , I have no information about this API endpoint . I am taking these API endpoints from the Discord Mobile Application and sharing them with you.
